service openstack-nova-api restart
service openstack-nova-cert restart
#service openstack-nova-compute restart
service openstack-nova-conductor restart
service openstack-nova-console restart
service openstack-nova-consoleauth restart
service openstack-nova-scheduler restart
service openstack-nova-novncproxy restart
service openstack-nova-network restart
